/*
 * This source file was generated by the Gradle 'init' task
 */
package eval1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test void Empacar_419() {
        App classUnderTest = new App();
        assertEquals(4, App.Empacar_choco(4, 1, 9));
    }


    @Test void Empacar_125() {
        App classUnderTest = new App();
        assertEquals(0, App.Empacar_choco(1, 2, 5));
    }

    @Test void Empacar_319() {
        App classUnderTest = new App();
        assertEquals(-1, App.Empacar_choco(3, 1, 9));
    }

    @Test void Empacar_9318() {
        App classUnderTest = new App();
        assertEquals(3, App.Empacar_choco(9, 3, 18));
    }

    @Test void Empacar_60100550() {
        App classUnderTest = new App();
        assertEquals(50, App.Empacar_choco(60, 100, 550));

    }

    @Test void Empacar_029() {
        App classUnderTest = new App();
        assertEquals(-1, App.Empacar_choco(0, 2, 9));

    }



}
